#!/bin/bash
# Set As Wallpaper
gsettings set org.gnome.desktop.background picture-uri file:///`pwd`/$1
sleep 5
# Make your wallpaper blurry
convert -blur 0x30 ~/.cache/wallpaper/* ~/Pictures/gdm_lock.jpg
# Copy wallpaper in system directory for gdm3 lockscreen 
cp -f ~/Pictures/gdm_lock.jpg /usr/share/backgrounds/

# Enjoy!
# My contact eugene.veprytskyi@gmail.com
